### ISSUE TITLE
Error when run in mac osx

### ISSUE THREAD

**Issue by stachera** [DataDog/datadog-trace-agent#397] opened 2018-03-09 22:37 UTC
./trace-agent-osx -config /opt/datadog-agent/etc/datadog.yaml

2018-03-09 19:33:06 INFO (main.go:142) - using legacy configuration from /opt/datadog-agent/etc/datadog.yaml
2018-03-09 19:33:06 INFO (agent.go:142) - error retrieving dd-agent hostname, falling back to os.Hostname(): exit status 1
2018-03-09 19:33:06 DEBUG (agent.go:315) - No aggregator configuration, using defaults
2018-03-09 19:33:06 ERROR (main.go:46) - you must specify an API Key, either via a configuration file or the DD_API_KEY env var

**Comment by wbarn** [comment] 2018-03-14 15:49
Same error here with the following:
- macos 10.13.3
- trace-agent 5.20.0
- datadog-agent 6.0.3

**Comment by catalinciurea** [comment] 2018-03-26 10:52
I am unable to run it at all. There is no trace-agent-osx executable.

make install triggers an error.

cmd/trace-agent/main.go:20:2: cannot find package "github.com/DataDog/datadog-agent/pkg/pidfile" in any of:
	/usr/local/opt/go/libexec/src/github.com/DataDog/datadog-agent/pkg/pidfile (from $GOROOT)

Setting $GOPATH to the unpacked dir still doesn't work. Is the dir structure right ? Is vendor dir supposed to be renamed to src ? Even so it still fails

cmd/trace-agent/agent.go:10:2: cannot find package "github.com/DataDog/datadog-trace-agent/config" in any of:
	/usr/local/opt/go/libexec/src/github.com/DataDog/datadog-trace-agent/config (from $GOROOT)

Thanks.

**Comment by dkavraal** [comment] 2018-04-03 15:35
Not working on mac

**Comment by noviceamateur** [comment] 2018-04-23 05:44
Getting similar error.
Will anyone take a look at this?
Its been open for a long time now.

Here are my logs ->

cannot find package "github.com/DataDog/datadog-agent/pkg/pidfile" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-agent/pkg/pidfile (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-agent/pkg/pidfile (from $GOPATH)
cmd/trace-agent/agent.go:10:2: cannot find package "github.com/DataDog/datadog-trace-agent/config" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/config (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/config (from $GOPATH)
cmd/trace-agent/agent.go:11:2: cannot find package "github.com/DataDog/datadog-trace-agent/filters" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/filters (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/filters (from $GOPATH)
cmd/trace-agent/agent.go:12:2: cannot find package "github.com/DataDog/datadog-trace-agent/info" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/info (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/info (from $GOPATH)
cmd/trace-agent/agent.go:13:2: cannot find package "github.com/DataDog/datadog-trace-agent/model" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/model (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/model (from $GOPATH)
cmd/trace-agent/agent.go:14:2: cannot find package "github.com/DataDog/datadog-trace-agent/quantizer" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/quantizer (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/quantizer (from $GOPATH)
cmd/trace-agent/agent.go:15:2: cannot find package "github.com/DataDog/datadog-trace-agent/sampler" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/sampler (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/sampler (from $GOPATH)
cmd/trace-agent/concentrator.go:11:2: cannot find package "github.com/DataDog/datadog-trace-agent/statsd" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/statsd (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/statsd (from $GOPATH)
cmd/trace-agent/agent.go:16:2: cannot find package "github.com/DataDog/datadog-trace-agent/watchdog" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/watchdog (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/watchdog (from $GOPATH)
cmd/trace-agent/agent.go:17:2: cannot find package "github.com/DataDog/datadog-trace-agent/writer" in any of:
	/usr/local/go/src/github.com/DataDog/datadog-trace-agent/writer (from $GOROOT)
	/Users/holani/go/src/github.com/DataDog/datadog-trace-agent/writer (from $GOPATH)
cmd/trace-agent/agent.go:8:2: cannot find package "github.com/cihub/seelog" in any of:
	/usr/local/go/src/github.com/cihub/seelog (from $GOROOT)
	/Users/holani/go/src/github.com/cihub/seelog (from $GOPATH)
cmd/trace-agent/receiver.go:17:2: cannot find package "github.com/tinylib/msgp/msgp" in any of:
	/usr/local/go/src/github.com/tinylib/msgp/msgp (from $GOROOT)
	/Users/holani/go/src/github.com/tinylib/msgp/msgp (from $GOPATH)
make: *** [install] Error 1

**Comment by catalinciurea** [comment] 2018-04-23 07:44
I managed to install it by ignoring the zip/tar.gz manually downloaded from github.com by running the following.

``` 
go get github.com/DataDog/datadog-trace-agent/cmd/trace-agent
cd $GOPATH/src/github.com/DataDog/datadog-trace-agent
make install
``` 

Then the agent is placed under `/opt/datadog-agent/embedded/bin`

**Comment by noviceamateur** [comment] 2018-04-23 11:15
Did that.

Getting new errors -

cmd/trace-agent/receiver.go:274:44: cannot use &servicesMeta (type model.ServicesMetadata) as type "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable in argument to decodeReceiverPayload:
model.ServicesMetadata does not implement "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable (wrong type for DecodeMsg method)
have DecodeMsg("github.com/DataDog/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Reader) error
want DecodeMsg("github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Reader) error
cmd/trace-agent/receiver.go:386:45: cannot use &traces (type *model.Traces) as type "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable in argument to decodeReceiverPayload:
model.Traces does not implement "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable (wrong type for DecodeMsg method)
have DecodeMsg("github.com/DataDog/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Reader) error
want DecodeMsg

**Comment by probert-mtv** [comment] 2018-04-25 15:55
Got the same problems. @catalinciurea tip works.

**Comment by gbbr** [comment] 2018-05-28 15:10
I've tested on my local macOS installation and everything seems to work fine. Can anyone help me reproduce this? I'd be happy to work together in finding a fix. I'd suggest trying a clean install. 

First, completely `rm -rf` your current installation. Then (as @catalinciurea already mentioned) try:
```
go get github.com/DataDog/datadog-trace-agent/cmd/trace-agent
cd $GOPATH/src/github.com/DataDog/datadog-trace-agent
make install
```

Let me know how that goes. If there's any error, please paste the (formatted) output.

**Comment by mateuspadua** [comment] 2018-06-17 15:27
After install, how can i run datadog trace agent, i dont find this command './trace-agent-osx-X.Y.Z -config /opt/datadog-agent/etc/datadog.conf'

**Comment by gbbr** [comment] 2018-06-18 08:46
@stachera do you still have this problem? It simply looks like you don't have the API key added in your config.

@mateuspadua sorry about that, it seems that when the release was made it was forgotten to add the binaries. I've added them now so it should be fix, please ping me if you're having issues. Just download your OS X binary [here](https://github.com/DataDog/datadog-trace-agent/releases/tag/6.2.1).

**Comment by gbbr** [comment] 2018-06-22 08:15
Going to close this. Binaries are added and instructions seem to be working fine now.

If anyone still has issues please feel free to reply or re-open.

**Closed by gbbr** 2018-06-22 08:15 UTC
Labels: bug
