### ISSUE TITLE
Issue with building trace agent for mac

### ISSUE THREAD

**Issue by noviceamateur** [DataDog/datadog-trace-agent#416] opened 2018-04-23 10:19 UTC
Sharads-MacBook-Pro:datadog-trace-agent holani$ make install
```
# prepares all dependencies by running the 'deps' task, generating
# versioning information and installing the binary.
go generate ./info
go install ./cmd/trace-agent
# github.com/datadog-trace-agent/cmd/trace-agent
cmd/trace-agent/receiver.go:274:44: cannot use &servicesMeta (type *model.ServicesMetadata) as type "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable in argument to decodeReceiverPayload:
        *model.ServicesMetadata does not implement "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable (wrong type for DecodeMsg method)
                have DecodeMsg(*"github.com/DataDog/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Reader) error
                want DecodeMsg(*"github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Reader) error
cmd/trace-agent/receiver.go:386:45: cannot use &traces (type *model.Traces) as type "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable in argument to decodeReceiverPayload:
        *model.Traces does not implement "github.com/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Decodable (wrong type for DecodeMsg method)
                have DecodeMsg(*"github.com/DataDog/datadog-trace-agent/vendor/github.com/tinylib/msgp/msgp".Reader) error
                want DecodeMsg
```

**Comment by gbbr** [comment] 2018-05-28 09:07
This looks like a duplicate of https://github.com/DataDog/datadog-trace-agent/issues/397...

When I run the following commands:
```
go get github.com/DataDog/datadog-trace-agent/...
cd datadog-trace-agent
make install
```
Everything finishes successfully. I'm trying to reproduce your issue but I can't. Can you provide more guidance?

**Comment by gbbr** [comment] 2018-05-28 09:09
Looking at your output, it seems like you have a problem in your $GOPATH, the agent should be installed in `$GOPATH/src/github.com/DataDog/datadog-trace-agent` and not `$GOPATH/src/github.com/datadog-trace-agent`.

**Comment by gbbr** [comment] 2018-05-28 09:10
Closing since the path seems to be problematic in this bug, please re-open if the error continues after trying out the suggested solution.

**Closed by gbbr** 2018-05-28 09:10 UTC
